# Config for CI pipeline
# this should mostly mirror the _config.yml exept it does not execute the cells
title: Machine Learning for Data Science Master
author: Johannes Maucher
logo: hdmlogomed.jpg

bibtex_bibfiles:
  - maucherML.bib

execute:
  execute_notebooks: "off"

parse:
  myst_url_schemes: [mailto, http, https]
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

sphinx:
    config:
      html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

latex:
  latex_documents:
    targetname: playgroundbook.tex
